# Generated by Django 5.2.7 on 2025-11-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0004_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
