# Generated by Django 5.2.7 on 2025-11-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0005_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
