# Generated by Django 5.2.7 on 2025-12-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0008_orderitem_status_orderitem_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
