# Generated by Django 5.2.7 on 2025-12-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0010_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='e_app_produ_price_c41b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='e_app_produ_created_fca6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='e_app_produ_is_acti_76095f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'price'], name='e_app_produ_categor_675fc7_idx'),
        ),
    ]
