# Generated by Django 5.2.7 on 2025-12-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0011_alter_product_price_alter_productimage_is_primary_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='e_app_produ_slug_8aca1d_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('vendor', 'slug'), name='unique_vendor_product_slug'),
        ),
    ]
