# Generated by Django 5.2.7 on 2026-02-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0013_alter_order_total_amount_alter_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product', 'is_primary'), name='unique_primary_image_per_product'),
        ),
    ]
