# Generated by Django 5.2.7 on 2026-02-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0014_productimage_unique_primary_image_per_product'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_primary_image_per_product',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_image_per_product'),
        ),
    ]
