# Generated by Django 5.2.7 on 2026-02-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0015_remove_productimage_unique_primary_image_per_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(verbose_name='image'),
        ),
    ]
