# Generated by Django 5.2.7 on 2026-02-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0016_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
